merchex/urls.py
from listings import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', views.band_list, name='home'),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_change, name='band-change'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change/', views.listing_change, name='listing-change'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),

    path('about-us/', views.about, name='about-us'),

    path('contact-us/', views.contact, name='contact-us'),
    path('email-sent/', views.email_sent, name='email-sent'),

    path('admin/', admin.site.urls)
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# listings/models.py

class Band(models.Model):
    def __str__(self):
        return f'{self.name}'

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

class Listing(models.Model):
    def __str__(self):
        return f'{self.title}'

    class Type(models.TextChoices):
        RECORDS = 'RC'
        CLOTHING = 'CH'
        POSTERS = 'PS'
        MISCELLANEOUS = 'MS'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2022)], 
    null=True, blank=True
    )
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, blank=True, on_delete=models.SET_NULL) 

listings/forms.py
# listings/forms.py

from django import forms
from listings.models import Band
from listings.models import Listing

class ContactUsForm(forms.Form):
   nom = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
   class Meta:
     model = Band
     fields = '__all__'
     labels = {
        "name": "Nom",
        "biography":"Biographie",            #Tradution
        "year_formed":"Année de formation",
        "official_homepage":"Page officiel"
      }

class ListingForm(forms.ModelForm):
   class Meta:
     model = Listing
     fields = '__all__'
     labels = {
        "title": "Titre",
        "sold":"Vendus",            #Tradution
        "year":"Année",
        "official_homepage":"Page officiel",
        "band":"Groupe"
      }

listings/views.py
from django.http import HttpResponse
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing
from django.http import Http404
from django.core.mail import send_mail
from django.shortcuts import redirect       #utile !!!!!!!!!!!!!!!!!!!!!!!!!!!

from listings.forms import ContactUsForm
from listings.forms import BandForm
from listings.forms import ListingForm

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands' : bands})

def band_detail(request, id):
    try:
        band = Band.objects.get(id=id)
        return render(request, 'listings/band_detail.html', {'band' : band})
    except Band.DoesNotExist:
        raise Http404('404 : Groupe inconnu...')
        #Ou autre template ??

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request, 'listings/band_create.html', {'form': form})

def band_change(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_change.html', {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request, 'listings/band_delete.html', {'band': band})

def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings' : listings})

def listing_detail(request, id):
        try:
            listing = Listing.objects.get(id=id)
            return render(request, 'listings/listing_detail.html', {'listing' : listing})
        except Band.DoesNotExist:
            raise Http404('404 : Groupe inconnu...')
            #Ou autre template ??
    
def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer---------------------------
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm()

    return render(request, 'listings/listing_create.html', {'form': form})

def listing_change(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request, 'listings/listing_change.html', {'form': form})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        listing.delete()
        # rediriger vers la liste des groupes
        return redirect('listing-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request, 'listings/listing_delete.html', {'listing': listing})

def about(request):
    return render(request, 'listings/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)  # ajout d’un nouveau formulaire ici

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'])

            return redirect('email-sent')
    
    else:
        form = ContactUsForm()

    return render(request,
          'listings/contact.html',
          {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

listings/templates/listings/about.html
{% extends 'listings/base.html' %} {% block content %}

<h1>À propos</h1>
<br>
<div class="card card-content">
    <p>Site developpé par 4lexDel dans le but de comprendre le framework Django</p>
</div>

{% endblock %}

listings/templates/listings/band_change.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Modifier un groupe</h1>
<br>
<div class="card card-content">
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Soumettre">
    </form>
</div>

{% endblock %}

listings/templates/listings/band_create.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Créer un groupe</h1>
<br>
<div class="card card-content">
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Soumettre">
    </form>
</div>

{% endblock %}

listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Supprimer le groupe</h1>

<div class="card card-content">
    <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>
    <a href="{% url 'band-list' %}">Retourner à la liste des groupes</a>
</div>

{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %} {% block content %}

<div class="card">
    <h2>{{ band.name }}</h2>
    <div class="card-content">
        <h3>Informations diverses</h3>

        <ul>
            <li>Genre : {{ band.get_genre_display }}</li>
            <li>Année de formation : {{ band.year_formed }}</li>
            <li>Actif : {{ band.active|yesno }}</li>
            {% if band.official_homepage %}
            <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
            {% endif %}
        </ul>

        <p>Biographie : {{ band.biography }}</p>

        <h3>Article(s) en lien avec l'artiste : </h3>
        <ul>
            {% for listing in band.listing_set.all %}
            <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{% url 'band-change' band.id %}">Editer le groupe</a>
        <a href="{% url 'band-delete' band.id %}">Supprimer le groupe</a>
        <a href="{% url 'band-list' %}">Retourner à la liste des groupes</a>
    </div>
</div>

{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Groupes</h1>
<br>
<div class="card card-content">
    <ul>
        {% for band in bands %}
        <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a> - <a href="{% url 'band-change' band.id %}">[Editer]</a></li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
</div>

{% endblock %}

listings/templates/listings/base.html
{% load static %}
<html>

<head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>

<body>
    <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'listing-list' %}">Articles</a>
        <a href="{% url 'contact-us' %}">Contact</a>
        <a href="{% url 'about-us' %}">A propos</a>
    </nav>
    <br><br>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>

</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Contact us</h1>

<div class="card card-content">
    <p>Nous sommes là pour vous aider.</p>

    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
</div>

{% endblock %}

listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Email envoyé avec succès !</h1>

<div class="card">
    <a href="{% url 'home' %}">Retour sur le site</a>
</div>

{% endblock %}

listings/templates/listings/listing_change.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Modifier un article</h1>
<br>
<div class="card card-content">
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Soumettre">
    </form>
</div>

{% endblock %}

listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Créer un article</h1>
<br>
<div class="card card-content">
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Soumettre">
    </form>
</div>

{% endblock %}

listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Supprimer l'article</h1>

<div class="card card-content">
    <p>Etes-vous sûr de vouloir supprimer l'article : {{ listing.title }} ?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>
    <a href="{% url 'listing-list' %}">Retourner à la liste des articles</a>
</div>

{% endblock %}

listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %} {% block content %}

<div class="card">
    <h2>{{ listing.title }}</h2>

    <div class="card-content">
        <h3>Informations diverses</h3>

        <ul>
            <li>Description : {{ listing.description }}</li>
            <li>Année : {{ listing.year }}</li>
            <li>Vendus : {{ listing.sold|yesno }}</li>
            <li>Type : {{ listing.get_type_display }}</li>
            {% if listing.band %}
            <li>Artiste : <a href="{% url 'band-detail' listing.band.id %}">{{ listing.band }}</a></li>
            {% endif %}
        </ul>

        <a href="{% url 'listing-change' listing.id %}">Editer l'article</a>
        <a href="{% url 'listing-delete' listing.id %}">Supprimer l'article</a>
        <a href="{% url 'listing-list' %}">Retourner à la liste des articles</a>
    </div>
</div>

{% endblock %}

listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %} {% block content %}

<h1>Articles</h1>

<div class="card card-content">
    <ul>
        {% for listing in listings %}
        <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a> - <a href="{% url 'listing-change' listing.id %}">[Editer]</a></li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'listing-create' %}">Créer un nouveau groupe</a>
</div>

{% endblock %}